spring.application.name=user-service
jwt.secret: minha-chave-super-secreta-123456

# gRPC server configuration
spring.grpc.server.port=9091

# Mongodb configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# GraphQL configuration
spring.graphql.graphiql.enabled=true


