spring.application.name=order-service
jwt.secret: minha-chave-super-secreta-123456

# gRPC client configuration
spring.grpc.client.channels.user-service.address=static://localhost:9091

# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Mongodb configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# GraphQL configuration
spring.graphql.graphiql.enabled=true
