spring.application.name=restaurant-service
jwt.secret: minha-chave-super-secreta-123456

# gRPC server configuration
spring.grpc.server.port=9090
spring.grpc.client.channels.user-service.address=static://user-service:9091



# GraphQL configuration
spring.graphql.graphiql.enabled=true


